from docx import Document
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os
import subprocess
import time

def docx_to_pdf(input_file: str, output_file: str):
    try:
        output_dir = os.path.dirname(output_file)
        base_name = os.path.splitext(os.path.basename(input_file))[0]
        generated_pdf = os.path.join(output_dir, base_name + ".pdf")

        command = [
            "soffice",
            "--headless",
            "--convert-to", "pdf",
            input_file,
            "--outdir", output_dir
        ]

        subprocess.run(command, check=True)

        # Esperar a que LibreOffice termine de escribir el archivo
        timeout = 10
        start_time = time.time()

        while not os.path.exists(generated_pdf):
            if time.time() - start_time > timeout:
                raise Exception("PDF was not generated by LibreOffice")
            time.sleep(0.5)

        # Renombrar al nombre final que usa la API
        os.rename(generated_pdf, output_file)

    except subprocess.CalledProcessError:
        raise Exception("Error converting DOCX to PDF with LibreOffice")

def docx_to_txt(input_file: str, output_file: str):
    document = Document(input_file)

    with open(output_file, "w", encoding="utf-8") as f:
        for para in document.paragraphs:
            text = para.text.strip()
            if text:
                f.write(text + "\n")

def docx_to_html(input_file: str, output_file: str):
    try:
        output_dir = os.path.dirname(output_file)
        base_name = os.path.splitext(os.path.basename(input_file))[0]
        generated_html = os.path.join(output_dir, base_name + ".html")

        command = [
            "soffice",
            "--headless",
            "--convert-to", "html",
            input_file,
            "--outdir", output_dir
        ]

        subprocess.run(command, check=True)

        # Esperar a que el archivo exista
        timeout = 10
        start_time = time.time()

        while not os.path.exists(generated_html):
            if time.time() - start_time > timeout:
                raise Exception("HTML was not generated")
            time.sleep(0.5)

        os.rename(generated_html, output_file)

    except subprocess.CalledProcessError:
        raise Exception("Error converting DOCX to HTML with LibreOffice")

def docx_to_md(input_file: str, output_file: str):
    document = Document(input_file)

    md_content = ""

    for para in document.paragraphs:
        text = para.text.strip()
        if not text:
            continue

        # Detectar títulos simples (muy básico)
        if para.style.name.startswith("Heading"):
            md_content += f"# {text}\n\n"
        else:
            md_content += f"{text}\n\n"

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(md_content)
